parameters:
    app.domain.sub_courses_domain.class: AppBundle\Domain\SubCourses\SubCoursesDomain
    app.domain.notifications_domain.class: AppBundle\Domain\Notifications\NotificationsDomain

services:
    app.domain.notifications_domain:
         class: "%app.domain.notifications_domain.class%"
         arguments:
             - "@app.repository.notifications"

    app.domain.ebooks_domain:
         class: "%app.domain.sub_courses_domain.class%"
         arguments:
             - "@app.repository.sub_courses"
             - "@app.repository.notes"
             - "@app.repository.questions"
