parameters:
    app.repository.sub_courses.class: AppBundle\Entity\Repository\SubCoursesRepository
    app.entity.sub_courses.class: AppBundle\Entity\SubCourses

    app.repository.notes.class: AppBundle\Entity\Repository\NotesRepository
    app.entity.notes.class: AppBundle\Entity\Notes

    app.repository.questions.class: AppBundle\Entity\Repository\QuestionsRepository
    app.entity.questions.class: AppBundle\Entity\Questions

    app.repository.favorites.class: AppBundle\Entity\Repository\FavoritesRepository
    app.entity.favorites.class: AppBundle\Entity\Favorites

    app.repository.user_question_answer_test.class: AppBundle\Entity\Repository\UserQuestionAnswerTestRepository
    app.entity.user_question_answer_test.class: AppBundle\Entity\UserQuestionAnswerTest

    app.repository.repeated_questions.class: AppBundle\Entity\Repository\RepeatedQuestionsRepository
    app.entity.repeated_questions.class: AppBundle\Entity\RepeatedQuestions

    app.repository.notifications.class: AppBundle\Entity\Repository\NotificationsRepository
    app.entity.notifications.class: AppBundle\Entity\Notifications

    app.repository.question_answers.class: AppBundle\Entity\Repository\QuestionAnswersRepository
    app.entity.question_answers.class: AppBundle\Entity\QuestionAnswers

    app.repository.votes.class: AppBundle\Entity\Repository\VotesRepository
    app.entity.votes.class: AppBundle\Entity\Votes

services:
    app.repository.votes:
        class: "%app.repository.votes.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.votes.class%"

    app.repository.question_answers:
        class: "%app.repository.question_answers.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.question_answers.class%"

    app.repository.notifications:
        class: "%app.repository.notifications.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.notifications.class%"

    app.repository.repeated_questions:
        class: "%app.repository.repeated_questions.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.repeated_questions.class%"

    app.repository.user_question_answer_test:
        class: "%app.repository.user_question_answer_test.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.user_question_answer_test.class%"

    app.repository.favorites:
        class: "%app.repository.favorites.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.favorites.class%"

    app.repository.sub_courses:
        class: "%app.repository.sub_courses.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.sub_courses.class%"

    app.repository.notes:
        class: "%app.repository.notes.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.notes.class%"

    app.repository.questions:
        class: "%app.repository.questions.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.questions.class%"