parameters:
    app.repository.sub_courses.class: AppBundle\Entity\Repository\SubCoursesRepository
    app.entity.sub_courses.class: AppBundle\Entity\SubCourses

    app.repository.notes.class: AppBundle\Entity\Repository\NotesRepository
    app.entity.notes.class: AppBundle\Entity\Notes

    app.repository.questions.class: AppBundle\Entity\Repository\QuestionsRepository
    app.entity.questions.class: AppBundle\Entity\Questions

services:
    app.repository.sub_courses:
        class: "%app.repository.sub_courses.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.sub_courses.class%"

    app.repository.notes:
        class: "%app.repository.notes.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.notes.class%"

    app.repository.questions:
        class: "%app.repository.questions.class%"
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - "%app.entity.questions.class%"