security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

        AppBundle\Entity\Admin:
            algorithm: bcrypt

    providers:
        chain_provider:
            chain:
                providers: [admins, entity_provider]

        admins:
            entity:
                class: AppBundle:Admin
                property: email

        entity_provider:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true

        api_admin:
            pattern:   ^/api/admin
            stateless: true
            anonymous: false
            provider: chain_provider
            guard:
                authenticators:
                    - app.jwt_token_authenticator

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: _email
                password_parameter: _password
                success_handler: custom
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/api/registrations
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: chain_provider
            guard:
                authenticators:
                    - app.jwt_token_authenticator

    access_control:
        - { path: ^/courses_of_study, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/registrations, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admins/user, roles: ROLE_ADMIN }
        - { path: ^/api/admins/role, roles: ROLE_ADMIN }
        - { path: ^/api/admins, roles: [ROLE_ADMIN, ROLE_COURSE_COMMITEE] }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
