services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    app_serialize.object_constructor:
        class: AppBundle\Serializer\Construction\DoctrineObjectConstructor
        public: false
        arguments:
            - "@doctrine"
            - "@jms_serializer.unserialize_object_constructor"

    jms_serializer.object_constructor:
        public: false
        alias: app_serialize.object_constructor

    gesdinet.jwtrefreshtoken.send_token:
        class: AppBundle\Security\AttachRefreshTokenOnSuccessListener
        arguments: [ "@gesdinet.jwtrefreshtoken.refresh_token_manager", "%gesdinet_jwt_refresh_token.ttl%", "@validator", "@request_stack" ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: attachRefreshToken }