services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]

    app_serialize.object_constructor:
        class: AppBundle\Serializer\Construction\DoctrineObjectConstructor
        public: false
        arguments:
            - "@doctrine"
            - "@jms_serializer.unserialize_object_constructor"

    jms_serializer.object_constructor:
        public: false
        alias: app_serialize.object_constructor

    app.doctrine_listener:
        class: AppBundle\Listener\DoctrineListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: doctrine.event_subscriber, connection: default }