<?php

namespace AppBundle\Entity\Repository;

/**
 * AppealsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppealsRepository extends \Doctrine\ORM\EntityRepository
{
}
