<?php

namespace AppBundle\Entity\Repository;

/**
 * CoursesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesRepository extends \Doctrine\ORM\EntityRepository
{
}
