<?php

namespace AppBundle\Entity\Repository;

/**
 * CoursesOfStudyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursesOfStudyRepository extends \Doctrine\ORM\EntityRepository
{
}
