<?php

namespace AppBundle\Entity\Repository;

/**
 * ExamPeriodsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamPeriodsRepository extends \Doctrine\ORM\EntityRepository
{
}
