<?php

namespace AppBundle\Entity\Repository;

/**
 * LectorsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LectorsRepository extends \Doctrine\ORM\EntityRepository
{
}
