<?php

namespace AppBundle\Entity\Repository;

/**
 * QuestionAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
