<?php

namespace AppBundle\Entity\Repository;

/**
 * RepeatedQuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepeatedQuestionsRepository extends \Doctrine\ORM\EntityRepository
{
}
