<?php

namespace AppBundle\Entity\Repository;

/**
 * ReportsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportsRepository extends \Doctrine\ORM\EntityRepository
{
}
