<?php

namespace AppBundle\Entity\Repository;

/**
 * SemestersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestersRepository extends \Doctrine\ORM\EntityRepository
{
}
