<?php

namespace AppBundle\Entity\Repository;

/**
 * UserQuestionAnswerOpenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserQuestionAnswerOpenRepository extends \Doctrine\ORM\EntityRepository
{
}
