api_users_registration:
    type: rest
    prefix:   /api
    resource: "@AppBundle/Controller/Api/RegistrationController.php"

api_users_auth:
    type: annotation
    prefix:   /
    resource: "@AppBundle/Controller/Api/AuthController.php"
    defaults: {_format: json}

api_users:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/UserController.php"

api_roles:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/RoleController.php"

api_courses_of_study:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/CoursesOfStudyController.php"

api_courses:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/CoursesController.php"

api_semesters:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/SemestersController.php"

api_lectors:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/LectorsController.php"

api_exam_periods:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/ExamPeriodsController.php"

api_sub_courses:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/SubCoursesController.php"

api_questions:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/QuestionsController.php"

api_notes:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/NotesController.php"

api_favorites:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/FavoritesController.php"

api_comments:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/CommentsController.php"
