api_users_registration:
    type: rest
    prefix:   /api
    resource: "@AppBundle/Controller/Api/RegistrationController.php"

api_users_auth:
    type: annotation
    prefix:   /
    resource: "@AppBundle/Controller/Api/AuthController.php"
    defaults: {_format: json}

api_users:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/UserController.php"

api_roles:
    type: rest
    prefix:   /
    resource: "@AppBundle/Controller/Api/RoleController.php"
