parameters:
    app.jwt_authenticator.class: AppBundle\Security\Guard\JWTAuthenticator
    app.object_manager.class: AppBundle\Services\ObjectManager
    app.authentication_success_handler.class: AppBundle\Security\AuthenticationSuccessHandler

services:

    app.jwt_token_authenticator:
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        class: "%app.jwt_authenticator.class%"

    app.auth:
        class: "%app.object_manager.class%"
        arguments:
            - "@jms_serializer"
            - "@validator"
            - "@request_stack"
            - "@security.token_storage"

    custom:
        class: "%app.authentication_success_handler.class%"
        arguments:
            - "@lexik_jwt_authentication.jwt_manager"
            - "@event_dispatcher"
        tags:
            - { name: monolog.logger, channel: security }