imports:
    - { resource: services/application.yml }
    - { resource: services/domain.yml }
    - { resource: services/repository.yml }

parameters:
    app.jwt_authenticator.class: AppBundle\Security\Guard\JWTAuthenticator
    app.object_manager.class: AppBundle\Services\ObjectManager
    app.authentication_success_handler.class: AppBundle\Security\AuthenticationSuccessHandler
    app.file_uploader.class: AppBundle\Helper\FileUploader
    app.serialization_listener.class: AppBundle\Listener\SerializationListener
    app.additional_function.class:  AppBundle\Helper\AdditionalFunction

services:
    app.listener.serializationlistener:
        class: "%app.serialization_listener.class%"
        arguments:
            - "@security.token_storage"
            - "@app.repository.notes"
            - "@app.repository.favorites"
            - "@app.repository.user_question_answer_test"
            - "@app.repository.repeated_questions"
            - "@app.repository.votes"
            - "@doctrine.orm.default_entity_manager.delegate"
        tags:
            - {name: jms_serializer.event_subscriber}

    app.jwt_token_authenticator:
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        class: "%app.jwt_authenticator.class%"

    app.auth:
        class: "%app.object_manager.class%"
        arguments:
            - "@jms_serializer"
            - "@validator"
            - "@request_stack"
            - "@security.token_storage"

    custom:
        class: "%app.authentication_success_handler.class%"
        arguments:
            - "@lexik_jwt_authentication.jwt_manager"
            - "@event_dispatcher"
        tags:
            - { name: monolog.logger, channel: security }

    app.file_uploader:
        class: "%app.file_uploader.class%"
        arguments:
            - "@gaufrette.local_storage_filesystem"

    app.additional_function:
        class: "%app.additional_function.class%"